### PR TITLE
Beginner guide to open source software article

### PR DESCRIPTION
**Pull request by Umayarz18**
Draft of my very lengthy beginners article open source contributions

### CODE REVIEW

**Comment by bjcarlson42** [comment]
@Umayarz18 Looking forward to the finished project of this article! Just wanted to let you know a few things. 

First, I noticed that you made some new tags. This is completely fine, however please make sure they are separated by dashes. For example, `open source` should be `open-source`. Also, each tag needs to have a corresponding `mdx` file inside of the tags folder. Since all 3 of your tags are new, you will need to add a file for each of the tags.

Lastly, `seoDescription` is now depreciated. We just use `description` now.

I also added a new contributions page which can be found here: https://benjamincarlson.notion.site/Contributing-to-Coffeeclass-io-27ab5e894368424a9c86a7f11555514b 

I am also making a new agile roadmap which can be found here: https://www.notion.so/benjamincarlson/2356b55aadf840f892b12f80531fe293?v=ddd300f3bb7c4d199f1abf6f770dd301 

I am hoping that both of these will make contributions easier. If there is anything you think is unclear, I would love to hear your thoughts!

**Comment by Umayarz18** [comment]
@bjcarlson42  oh cool, thanks for letting me know! I will make sure to have tags and try to keep the article from being more than 2000 words (lots of material to write about lol). Honestly if it goes longer, it might even be better to shorten this article to 1400 words  and save some points of an open-source course in the future. Let me know if that sounds like a good approach to you to have a shorter beginner's article and like a 6 module open source course to best educate on the topic?

**Comment by bjcarlson42** [comment]
That sounds like a great idea. Would you be willing to create the course?

**Comment by Umayarz18** [comment]
Yes, I don't mind 😄. After my full article is done, I will see how I could structure most of it into a course on like a doc and I'll post the outline to the discussion board to get feedback.

**Comment by bjcarlson42** [comment]
Sounds good! @Umayarz18

**Comment by bjcarlson42** [comment]
Hey @Umayarz18 Is this PR ready for review or is it still a draft?

**Comment by Umayarz18** [comment]
Yes, I condensed it a bit more to leave some ideas for a course. But it's good for review now 😄

**Comment by bjcarlson42** [comment]
@Umayarz18 article looks good. Can you merge main into your branch? There were some commits made to main that happened after you created this branch. After that, I'll merge!

**Comment by Umayarz18** [comment]
Okay just updated to match main,  list items seem to look off but I'm not quite sure why.
image

**Pull request merged**
