### PR TITLE
Added Image option for articles

### PR DESCRIPTION
**Pull request by Umayarz18**
Article writers can now add image to their mdx articles and the SEO component will use the image as the OG:Image.

The [slug].js for articles will now display an image if provided.

## Example Article with Image
image

### CODE REVIEW

**Comment by bjcarlson42** [comment]
This is good but I am not liking how the image is displayed. For one, we should not display the logo image AND the feature image. This looks odd. Maybe if there is a feature image use that, if not use the logo? Or, is there a way to have them together and look nice? I am not sure. Do you have any ideas? Lastly, can we use `NextImage` to display the image? It is better for seo, load time, layout shift etc.

**Comment by Umayarz18** [comment]
Yeah I agree its weird. I'll see if there's a way to convert the logo image to an OG:Image that includes the title similar to how Github generates for issues and pull requests.

**Comment by bjcarlson42** [comment]
Could you elaborate on what GitHub does? I'm not familiar with it.

**Comment by bjcarlson42** [comment]
That is actually really cool! The blog post mentions Vercel ogimage - https://github.com/vercel/og-image Maybe this could work?

**Comment by bjcarlson42** [comment]
@Umayarz18 I just merged your other pull request (the guide to oss article). As for this PR, maybe we want to merge now and then create a new PR for the Open Graph image using https://github.com/vercel/og-image? I think we can actually go ahead and delete the feature images for now.

**Pull request closed without merging**
